"""created item and itemsininventory models

Revision ID: 9d3830042a9b
Revises: 8dccc6c1e923
Create Date: 2023-10-07 14:50:51.122545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9d3830042a9b"
down_revision: Union[str, None] = "8dccc6c1e923"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "steamitems",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("app_id", sa.Integer(), nullable=False),
        sa.Column("classid", sa.Integer(), nullable=False),
        sa.Column("first_item_cost", sa.Integer(), nullable=False),
        sa.Column("item_cost", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("classid"),
    )
    op.create_table(
        "steamitemsininventorys",
        sa.Column("amount", sa.Integer(), nullable=True),
        sa.Column("inventory_id", sa.Integer(), nullable=True),
        sa.Column("item_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["inventory_id"], ["steaminventorys.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["item_id"], ["steamitems.classid"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("item_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("steamitemsininventorys")
    op.drop_table("steamitems")
    # ### end Alembic commands ###
