"""added time column in Game model

Revision ID: ca391be7df9e
Revises: 14b5232421c3
Create Date: 2023-10-02 02:32:31.540371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ca391be7df9e"
down_revision: Union[str, None] = "14b5232421c3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("games", sa.Column("time_in_game", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("games", "time_in_game")
    # ### end Alembic commands ###
