"""added GameInAccount

Revision ID: 8cd05fe6d56b
Revises: 39649bc2b8ef
Create Date: 2023-11-20 20:51:57.387879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8cd05fe6d56b"
down_revision: Union[str, None] = "39649bc2b8ef"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gameinaccounts",
        sa.Column("first_game_cost", sa.Integer(), nullable=True),
        sa.Column("time_in_game", sa.Integer(), nullable=True),
        sa.Column("steam_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["steam_id"], ["steamids.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_constraint("games_steam_id_fkey", "games", type_="foreignkey")
    op.drop_column("games", "steam_id")
    op.drop_column("games", "time_in_game")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "games",
        sa.Column("time_in_game", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "games", sa.Column("steam_id", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.create_foreign_key(
        "games_steam_id_fkey",
        "games",
        "steamids",
        ["steam_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_table("gameinaccounts")
    # ### end Alembic commands ###
