"""added GameInAccount field(game_id)

Revision ID: 6b1625fbe863
Revises: 8cd05fe6d56b
Create Date: 2023-11-20 23:01:59.435731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6b1625fbe863"
down_revision: Union[str, None] = "8cd05fe6d56b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("gameinaccounts", sa.Column("game_name", sa.String(), nullable=True))
    op.add_column("gameinaccounts", sa.Column("game_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        None, "gameinaccounts", "games", ["game_id"], ["id"], ondelete="CASCADE"
    )
    op.alter_column("games", "game_id", existing_type=sa.INTEGER(), nullable=False)
    op.create_unique_constraint(None, "games", ["game_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "games", type_="unique")
    op.alter_column("games", "game_id", existing_type=sa.INTEGER(), nullable=True)
    op.drop_constraint(None, "gameinaccounts", type_="foreignkey")
    op.drop_column("gameinaccounts", "game_id")
    op.drop_column("gameinaccounts", "game_name")
    # ### end Alembic commands ###
