"""models simplification

Revision ID: 5b42bbf87506
Revises: 6407742694a1
Create Date: 2023-12-02 05:18:09.641274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5b42bbf87506"
down_revision: Union[str, None] = "6407742694a1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "gameinaccounts_game_id_fkey", "gameinaccounts", type_="foreignkey"
    )
    op.drop_constraint(
        "gameinaccounts_steam_id_fkey", "gameinaccounts", type_="foreignkey"
    )
    op.drop_column("gameinaccounts", "steam_id")
    op.drop_column("gameinaccounts", "game_id")
    op.drop_constraint("gametracks_game_id_fkey", "gametracks", type_="foreignkey")
    op.drop_constraint("gametracks_user_id_fkey", "gametracks", type_="foreignkey")
    op.drop_column("gametracks", "user_id")
    op.drop_column("gametracks", "game_id")
    op.drop_constraint("itemtracks_user_id_fkey", "itemtracks", type_="foreignkey")
    op.drop_constraint("itemtracks_item_id_fkey", "itemtracks", type_="foreignkey")
    op.drop_column("itemtracks", "item_id")
    op.drop_column("itemtracks", "user_id")
    op.drop_constraint("steamids_user_id_fkey", "steamids", type_="foreignkey")
    op.drop_column("steamids", "user_id")
    op.drop_constraint(
        "steaminventorys_steam_id_fkey", "steaminventorys", type_="foreignkey"
    )
    op.drop_column("steaminventorys", "steam_id")
    op.drop_constraint(
        "steamitemsininventorys_item_id_fkey",
        "steamitemsininventorys",
        type_="foreignkey",
    )
    op.drop_constraint(
        "steamitemsininventorys_inventory_id_fkey",
        "steamitemsininventorys",
        type_="foreignkey",
    )
    op.drop_column("steamitemsininventorys", "item_id")
    op.drop_column("steamitemsininventorys", "inventory_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "steamitemsininventorys",
        sa.Column("inventory_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "steamitemsininventorys",
        sa.Column("item_id", sa.BIGINT(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "steamitemsininventorys_inventory_id_fkey",
        "steamitemsininventorys",
        "steaminventorys",
        ["inventory_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "steamitemsininventorys_item_id_fkey",
        "steamitemsininventorys",
        "steamitems",
        ["item_id"],
        ["classid"],
        ondelete="CASCADE",
    )
    op.add_column(
        "steaminventorys",
        sa.Column("steam_id", sa.BIGINT(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "steaminventorys_steam_id_fkey",
        "steaminventorys",
        "steamids",
        ["steam_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.add_column(
        "steamids",
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "steamids_user_id_fkey", "steamids", "users", ["user_id"], ["id"]
    )
    op.add_column(
        "itemtracks",
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "itemtracks",
        sa.Column("item_id", sa.BIGINT(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "itemtracks_item_id_fkey",
        "itemtracks",
        "steamitems",
        ["item_id"],
        ["classid"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "itemtracks_user_id_fkey",
        "itemtracks",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.add_column(
        "gametracks",
        sa.Column("game_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "gametracks",
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "gametracks_user_id_fkey",
        "gametracks",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "gametracks_game_id_fkey",
        "gametracks",
        "games",
        ["game_id"],
        ["game_id"],
        ondelete="CASCADE",
    )
    op.add_column(
        "gameinaccounts",
        sa.Column("game_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "gameinaccounts",
        sa.Column("steam_id", sa.BIGINT(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "gameinaccounts_steam_id_fkey",
        "gameinaccounts",
        "steamids",
        ["steam_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "gameinaccounts_game_id_fkey",
        "gameinaccounts",
        "games",
        ["game_id"],
        ["game_id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
