"""delete uniqie field from steamitemininventories

Revision ID: 39649bc2b8ef
Revises: da741f4cc9af
Create Date: 2023-11-20 01:08:47.451792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "39649bc2b8ef"
down_revision: Union[str, None] = "da741f4cc9af"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "steamitemsininventorys_item_id_key", "steamitemsininventorys", type_="unique"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "steamitemsininventorys_item_id_key", "steamitemsininventorys", ["item_id"]
    )
    # ### end Alembic commands ###
