"""added first_cost field in ItemInInventory

Revision ID: 5246a0d58191
Revises: e8f1e548f8ad
Create Date: 2023-11-22 20:58:19.650832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5246a0d58191"
down_revision: Union[str, None] = "e8f1e548f8ad"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "gameinaccounts",
        "steam_id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=True,
    )
    op.alter_column(
        "steaminventorys",
        "steam_id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=True,
    )
    op.drop_column("steamitems", "first_item_cost")
    op.add_column(
        "steamitemsininventorys",
        sa.Column("first_item_cost", sa.Integer(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("steamitemsininventorys", "first_item_cost")
    op.add_column(
        "steamitems",
        sa.Column("first_item_cost", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.alter_column(
        "steaminventorys",
        "steam_id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    op.alter_column(
        "gameinaccounts",
        "steam_id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
