"""added inventory model

Revision ID: 8dccc6c1e923
Revises: ea2d472fd847
Create Date: 2023-10-05 19:08:39.628094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8dccc6c1e923"
down_revision: Union[str, None] = "ea2d472fd847"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "steaminventorys",
        sa.Column("games_id", sa.Integer(), nullable=False),
        sa.Column("first_inventory_cost", sa.Integer(), nullable=False),
        sa.Column("inventory_cost", sa.Integer(), nullable=False),
        sa.Column("steam_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["steam_id"], ["steamids.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.alter_column(
        "games",
        "steam_id",
        existing_type=sa.BIGINT(),
        type_=sa.Integer(),
        existing_nullable=True,
    )
    op.drop_constraint("games_steam_id_fkey", "games", type_="foreignkey")
    op.create_foreign_key(
        None, "games", "steamids", ["steam_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "games", type_="foreignkey")
    op.create_foreign_key(
        "games_steam_id_fkey", "games", "steamids", ["steam_id"], ["id"]
    )
    op.alter_column(
        "games",
        "steam_id",
        existing_type=sa.Integer(),
        type_=sa.BIGINT(),
        existing_nullable=True,
    )
    op.drop_table("steaminventorys")
    # ### end Alembic commands ###
