"""added GameInAccount field(game_id)

Revision ID: e8f1e548f8ad
Revises: 6b1625fbe863
Create Date: 2023-11-20 23:06:38.110900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e8f1e548f8ad"
down_revision: Union[str, None] = "6b1625fbe863"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "gameinaccounts_game_id_fkey", "gameinaccounts", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "gameinaccounts", "games", ["game_id"], ["game_id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "gameinaccounts", type_="foreignkey")
    op.create_foreign_key(
        "gameinaccounts_game_id_fkey",
        "gameinaccounts",
        "games",
        ["game_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
